### ISSUE TITLE
VPS upgrade to Ubuntu 18.04

### ISSUE THREAD

**Issue by ppigazzini** [glinscott/fishtest#408]
## People
- [x] @glinscott - VPS build
- [x] @ppigazzini - other tasks

### Date
16.11.2019
### Start time pre-upgrade task
10:30 UTC

### Start time upgrade task
11:00 UTC

### pre-upgrade
- [x] write setup_fishtest.sh
  - [x] with passwords and keys
  - [x] disable the fishtest start
  - [x] comment out all the crontab jobs
- [x] write the mongodb restore script
```bash
#!/bin/bash
# mongodb_restore.sh

bkp_dir=${HOME}/backup/restore
[ ! -d ${bkp_dir} ] && mkdir -p ${bkp_dir}
mv dump.tar.gz ${bkp_dir}
cd ${bkp_dir}
mongo fishtest         --eval 'db.dropDatabase()'
mongo fishtest_new     --eval 'db.dropDatabase()'
mongo fishtest_testing --eval 'db.dropDatabase()'

tar -xzvf dump.tar.gz && rm -f dump/*/*.json && mongorestore --drop
```
- [x]  write delete_old_users.sh
```bash
#!/bin/bash
# delete_old_users.sh
# remove old pending users (remove lines 154 to 158)

cd ~/fishtest/fishtest/utils
cp delta_update_users.py delete_old_users.py
vi delete_old_users.py << EOF
:154,158d
:154
2X
:155
.
:wq
EOF
$VENV/bin/python delete_old_users.py
```
- [x] utility scripts backup
- [x] make a gmail account for the Let's Encrypt certificate
- [x] forum post to alert for:
 - the downtime
 - the switch to https
- [x] comment out crontab jobs
- [x] stop fishtest
```bash
#!/bin/sh
cd ${HOME}/fishtest/fishtest
cp nohup.out ${HOME}/logs/nohup.out.$(date +%Y%m%d%H%M%S --utc)
pkill -f pserve
```
- [x] logs backup
- [x] mongodb backup on s3
```
bash ~/fishtest/fishtest/utils/backup.sh
```
- [x] mongodb dump download

### upgrade
- [x] new VPS Ubuntu 18.04 LTS
 - ssh access as or "root" or a new user in sudo group:
```bash
#!/bin/bash
user_name='vpsuser'
user_pwd='<vpsuser_password>'
useradd -m -s /bin/bash ${user_name}
echo ${user_name}:${user_pwd} | chpasswd
usermod -aG sudo ${user_name}
```
### post-upgrade
- [x] copy and launch the setup_fishtest.sh script
- [x] sshd_config hardening (public/private keys, AllowUsers, no root, no password, change port etc.)
- [x] mongodb dump upload and restore (with mongodb_restore.sh)
- [x] remove old pending users (with delete_old_users.sh)
- [x] start fishtest
- [x] enable the crontab jobs
- [x] fix the backup script
- [x] administration/utility scripts restore
- [x] forum post to update the status:
- [x] merge PRs: https://github.com/glinscott/fishtest/pull/43 https://github.com/glinscott/fishtest/pull/394
- [x] merge PRs: https://github.com/glinscott/fishtest/pull/383
- [x] start certbot to get the Let's Encrypt certificate
- [x] announce the switch to https for the worker

### todo
- [x] configure exim4 to send external/internal mail
- [x] move captcha under the new mail
- [x] delete old scripts:
~/fishtest/fishtest/start.sh
~/fishtest/fishtest/start_dev.sh
- [x] fishtest/fishtest/utils scripts: change shebang to `#!/usr/bin/env python`, change mode to 644
- [x] update SETUP
- [x] tune MongoDB/nginx/pserve
- [x] wiki update server setup

**Comment by tomtor** [comment]
@ppigazzini @glinscott I wonder if mailing will work on a fresh configured Ubuntu 18.04:

https://github.com/glinscott/fishtest/blob/2b4c830d1ab01fc5b9d5fca5f4a752a4c060c141/fishtest/fishtest/views.py#L901

Something to test?

**Comment by ppigazzini** [comment]
@tomtor /var/mail is empty on the dev-server, I will look this issue tonight

@glinscott if I'm not wrong you should be in UTC+7, I'm in UTC-2

@noobpwnftw please keep on eye on this issue

**Comment by tomtor** [comment]
> tonight I will look if the SMTP is working on the dev-server

@ppigazzini Yes, my and your dev-server did some posting: https://groups.google.com/forum/?fromgroups=#!searchin/fishcooking_results/user01%7Csort:date

but I have configured/installed postfix as internet mailer and I guess you did that too. Note that google will reject mail from IPv6 senders without additional authentication measures, so I forced the use of IPv4.

This mail stuff has low priority IMO so I suggest not spending too much time on it and give it some attention AFTER the upgrade.

**Comment by ppigazzini** [comment]
@tomtor added a task about the SMTP, the configuration could be already done in the ISP image.

I updated the server setup script (check the [wiki script](https://github.com/glinscott/fishtest/wiki/Fishtest-server-setup)) to use a custom username. In my dev server I don't use "fishtest" as username because:
 - I want to differentiate the prompts of prod/dev servers to avoid mistakes
 - I hate this path `/home/fishtest/fishtest/fishtest/fishtest` :)

**Comment by noobpwnftw** [comment]
Looks good to me, my workers may need some extra setup post upgrade and I'll look into it.

**Comment by ppigazzini** [comment]
@glinscott @tomtor @noobpwnftw 
upgrade scheduled for today:
* h 15:00 UTC pre upgrade tasks
* h 16:00 UTC upgrade

**Comment by ppigazzini** [comment]
Upgrade aborted for today.

The IPS can build a Ubuntu 18.04 only with a new IP address, so we need to involve in the upgrade process @daylen , the owner of stockfishchess, to update the DNS field of tests.stockfishchess.org.

**Comment by ppigazzini** [comment]
I'm in touch with @daylen for the upgrade.

**Comment by noobpwnftw** [comment]
@ppigazzini Alright, shall we halt all new tests for today, let the queue run dry and then retry upgrade at some point?

**Comment by tomtor** [comment]
Is the new 18.04 server already available?

**Comment by ppigazzini** [comment]
@noobpwnftw @tomtor no.
I have time to do the upgrade only during the weekend and with @daylen updating the DNS field I would like free @glinscott from the commitment of the VPS.

**Comment by tomtor** [comment]
Note that DNS propagation takes some time depending on the TTL setting. 
It would be wise to lower the TTL now so that the new IP propagates quickly as soon as the move is made.

**Comment by tomtor** [comment]
@ppigazzini @daylen I looked up the TTL:

Type | Mname | Rname | Serial | Refresh | Retry | Expire | Minimum | Name | Class | TTL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
SOA | jill.ns.cloudflare.com | dns.cloudflare.com | 2031175426 | 10000 | 2400 | 604800 | 3600 | stockfishchess.org | IN | 3599

That is just one hour (it is often much longer, eg 24 hours), so if the DNS is changed at the start of the upgrade, that should be OK.

**Comment by ppigazzini** [comment]
@noobpwnftw upgrade of fishtest server scheduled in 1 hour

**Comment by ppigazzini** [comment]
Upgrade to Ubuntu 18.04 finished.
Nearly 02:00 AM here, I will complete the tasklist after some sleeping to avoid a disaster :)

**Comment by ppigazzini** [comment]
@tomtor better to use this issue for the fine tuning of the new VPS setup. The subject of the old issue https://github.com/glinscott/fishtest/issues/423 was a nightmare for me :)

**Comment by tomtor** [comment]
@ppigazzini Ok, I copied my remark:

The query for finished runs in rundb.py around line 229:

    c = self.runs.find(q, skip=skip, limit=limit, sort=[('last_updated', DESCENDING)]) 

The sort would need to inspect ALL tests.

I wonder when that sort is removed, we might still get recent tests first, but in reverse order of creation instead of update.

Could you change the sort on the dev server to:

    c = self.runs.find(q, skip=skip, limit=limit, sort=[('$natural', DESCENDING)]) 

OR (if that does not work) to the similar:

    c = self.runs.find(q, skip=skip, limit=limit, sort=[('_id', DESCENDING)]) 

If either works then we can do the sort on last_updated for the retrieved 50 tests in Python to speed it up. The downside is that a really old test which just finished might end up on the second or even later page.

Note that older data is retrieved from `old_runs`, that is an emergency measure implemented by Gary the previous time the database grow too big:

https://github.com/glinscott/fishtest/blob/7db731d8685fee4b3ad5b905683eeae33f4f263a/fishtest/fishtest/rundb.py#L233

So a speed up could be to move some more data to that collection, see eg https://stackoverflow.com/questions/27039083/mongodb-move-documents-from-one-collection-to-another-collection/41483981#41483981

It would be better if we would not have to resort to such tricks, and adapt fishtest to deal with a large `runs` database, by adapting the `sort`.

**Comment by ppigazzini** [comment]
@snicolet @vondele https enabled for server and worker :)

**Comment by vondele** [comment]
I'm seeing the following from time to time (already pre https):

504 Gateway Time-out
nginx/1.14.0 (Ubuntu)

**Comment by tomtor** [comment]
@vondele @ppigazzini Building the main page can take over 30 seconds in some situations. I expect this exceeds the nginx timeout.

**Comment by xoto10** [comment]
It's possible one of the database queries is running differently from before, I assume we are using a newer version of mongodb?

**Comment by ppigazzini** [comment]
@xoto10 the SW stack is updated, MongoDB v. 4.2

**Comment by ppigazzini** [comment]
@xoto10 there is a problem with indexes, view https://github.com/glinscott/fishtest/pull/434
Any help is welcome :)

**Comment by xoto10** [comment]
@ppigazzini @tomtor 

> The query for finished runs in rundb.py around line 229:
> 
> ```
> c = self.runs.find(q, skip=skip, limit=limit, sort=[('last_updated', DESCENDING)]) 
> ```
...
> It would be better if we would not have to resort to such tricks, and adapt fishtest to deal with a large `runs` database, by adapting the `sort`.

I missed this when when reading through this issue earlier. The db should be able to do this query efficiently using the index on finished and last_updated. This would get progressively slower for later pages, but should be fine for the usual case of viewing the 1st page. If it isn't using the index or there is some other problem we should investigate.

**Comment by xoto10** [comment]
It's not surprising if the db upgrade has altered the way a/some queries are executed. Perhaps one query somewhere (perhaps an unusual one) is running VERY slowly now, and causing the whole thing to seize up occasionally. Just making educated guesses here.

**Comment by ppigazzini** [comment]
@tomtor after the debugging/improvement from #434 I'm trying this configuration:
* 3 pserve instances
* MongoDB cacheSizeGB 0.75

I viewed that 1 pserve instance got 45% RAM after 12 hours.

**Comment by ppigazzini** [comment]
@tomtor after 24 hours the server settled to 76% RAM level, I raised MongoDB cacheSizeGB 1.0 expecting an 81% RAM level. I will keep monitored the VPS during the next backup scheduled (23 minutes from now).

**Comment by tomtor** [comment]
@ppigazzini See also https://github.com/glinscott/fishtest/issues/440

**Comment by tomtor** [comment]
@ppigazzini just a note. History mail is not being sent.

I can have a look at it if you want.

**Comment by ppigazzini** [comment]
@tomtor I don't know the mail reporting process, so please have you a look at that :)
Let me know if I must update the setup script.

**Comment by tomtor** [comment]
@ppigazzini On the fishtest server generic mail sending for an Ubuntu server has to be configured. Fishtest will expect to be able to talk to a local SMTP server, see:
https://github.com/glinscott/fishtest/blob/be84f2aef00f3f9d5f2def39589d2900820a6964/fishtest/fishtest/views.py#L895

**Comment by ppigazzini** [comment]
@tomtor according to the GitHub documentation the address should be `fishtest@users.noreply.github.com`

https://github.com/glinscott/fishtest/blob/be84f2aef00f3f9d5f2def39589d2900820a6964/fishtest/fishtest/views.py#L916

https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address

```
Note: If you created your GitHub account after July 18, 2017, your GitHub-provided no-reply
email address is a seven-digit ID number and your username in the form of
ID+username@users.noreply.github.com.
If you created your GitHub account prior to July 18, 2017, your GitHub-provided no-reply
email address is your username in the form of username@users.noreply.github.com.
You can get an ID-based GitHub-provided no-reply email address by selecting (or deselecting
and reselecting) Keep my email address private in your email settings.
```

**Comment by ppigazzini** [comment]
@tomtor the VPS template has already installed exim4, here some documentation for the configuration
https://wiki.debian.org/Exim#Single_Exim4_configuration_file

**Comment by tomtor** [comment]
@ppigazzini generic mail is now working on prod, so you can send mails.

**Comment by ppigazzini** [comment]
Thank you @tomtor

**Comment by ppigazzini** [comment]
recaptcha moved under the new mail address, finally all task cleared :)
